#!/usr/bin/env python3
"""
Phase 2: Resource Isolation — Port Locking & Caddy Teardown
ADR-006 Implementation

Enforces exclusive resource binding per squad:
- Port ranges per project (PRJ-SAKK 8000-8099, PRJ-SYRH 8100-8199)
- Database socket per squad (_context/.locks/)
- Caddy subdomain isolation + auto-teardown
- Timeout guard: orphaned locks release after 4 hours
"""

import os
import json
import fcntl
import sys
import hashlib
import time
from datetime import datetime, timedelta
from pathlib import Path


def acquire_project_lock(prj_id, squad_id, timeout_minutes=240):
    """
    Acquire exclusive, non-blocking lock on port + DB resources for a project squad.
    If collision detected, fail with clear error + guidance.

    Lock format: ~/Desktop/Lorka/projects/.locks/{prj_id}.lock
    Contains manifest JSON: {squad_id, base_port, mysql_db, caddy_subdomain, acquired_at}
    """
    lock_dir = os.path.expanduser("~/Desktop/Lorka/projects/.locks")
    os.makedirs(lock_dir, exist_ok=True)
    lock_file_path = os.path.join(lock_dir, f"{prj_id}.lock")

    # Deterministic port range per project
    # Hash ensures consistent range even if multiple squads launch
    hash_digest = hashlib.md5(prj_id.encode()).hexdigest()
    port_offset = (int(hash_digest, 16) % 50) * 2
    base_port = 8000 + port_offset

    try:
        f = open(lock_file_path, "w")
        # Try exclusive, non-blocking lock (LOCK_EX | LOCK_NB)
        fcntl.flock(f, fcntl.LOCK_EX | fcntl.LOCK_NB)

        # Lock acquired. Write manifest.
        manifest = {
            "squad_id": squad_id,
            "base_port": base_port,
            "mysql_db": f"sofi_{prj_id.lower()}_test",
            "caddy_subdomain": f"{prj_id.lower()}.zanjour.local",
            "acquired_at": datetime.now().isoformat(),
            "timeout_minutes": timeout_minutes
        }

        f.write(json.dumps(manifest, indent=2))
        f.flush()

        print(f"[RESOURCE LOCK ACQUIRED]")
        print(f"  Squad: {squad_id}")
        print(f"  Project: {prj_id}")
        print(f"  Port: {base_port}")
        print(f"  Database: {manifest['mysql_db']}")
        print(f"  Caddy: {manifest['caddy_subdomain']}")

        return f, manifest

    except IOError as e:
        # Lock held by another squad. Check if stale.
        try:
            with open(lock_file_path, "r") as existing:
                existing_manifest = json.load(existing)
                acquired_at = datetime.fromisoformat(existing_manifest["acquired_at"])
                age_minutes = (datetime.now() - acquired_at).total_seconds() / 60

                if age_minutes > existing_manifest["timeout_minutes"]:
                    print(f"[STALE LOCK DETECTED] {prj_id} lock held for {age_minutes:.0f}m (timeout: {existing_manifest['timeout_minutes']}m)")
                    print(f"  Releasing stale lock and retrying...")
                    release_stale_lock(lock_file_path)
                    # Recursive retry
                    return acquire_project_lock(prj_id, squad_id, timeout_minutes)
                else:
                    print(f"[CRITICAL COLLISION] Resource lock for {prj_id} held by squad {existing_manifest['squad_id']}")
                    print(f"  Lock acquired {age_minutes:.1f}m ago")
                    print(f"  Action: Wait for squad to complete or use sofi dispatch --force-unlock {existing_manifest['squad_id']}")
                    sys.exit(1)
        except Exception:
            print(f"[CRITICAL COLLISION] Resource lock for {prj_id} held by another process")
            sys.exit(1)


def generate_dynamic_caddyfile(manifest):
    """
    Generate per-squad Caddy config, reload systemd.
    Creates reverse proxy from Caddy subdomain → localhost:{base_port}
    """
    caddy_conf_dir = "/etc/caddy/conf.d"
    os.makedirs(caddy_conf_dir, exist_ok=True)

    caddy_template = f"""
# Squad: {manifest['squad_id']}
# Auto-generated by caddy_isolation.py
# Tear down on squad completion

{manifest['caddy_subdomain']} {{
    reverse_proxy 127.0.0.1:{manifest['base_port']} {{
        header_up X-Forwarded-Host {{{{host}}}}
        header_up X-Forwarded-Port {{{{port}}}}
        header_up X-Forwarded-Proto {{{{scheme}}}}
    }}
}}
"""

    caddy_file = os.path.join(caddy_conf_dir, f"{manifest['squad_id']}.caddy")

    try:
        with open(caddy_file, "w") as cf:
            cf.write(caddy_template)

        # Reload Caddy
        result = os.system("systemctl reload caddy 2>/dev/null")
        if result == 0:
            print(f"[CADDY LOADED] {manifest['caddy_subdomain']} → localhost:{manifest['base_port']}")
        else:
            print(f"[CADDY WARNING] Reload may have failed (exit {result}). Check systemctl status caddy.")
    except PermissionError:
        print(f"[WARNING] Cannot write Caddy config (requires sudo). Manual setup needed:")
        print(f"  File: {caddy_file}")
        print(f"  {caddy_template}")


def release_project_lock(lock_file_obj, squad_id, manifest):
    """
    Release lock, tear down Caddy config.
    Called on squad completion or explicit cleanup.
    """
    if lock_file_obj:
        fcntl.flock(lock_file_obj, fcntl.LOCK_UN)
        lock_file_obj.close()

    # Remove Caddy config
    caddy_file = f"/etc/caddy/conf.d/{squad_id}.caddy"
    try:
        if os.path.exists(caddy_file):
            os.remove(caddy_file)
            os.system("systemctl reload caddy 2>/dev/null")
            print(f"[CADDY TORN DOWN] {manifest['caddy_subdomain']}")
    except PermissionError:
        print(f"[WARNING] Cannot remove Caddy config (requires sudo). Manual cleanup: rm {caddy_file}")

    print(f"[RESOURCE CLEANUP] Squad {squad_id} released. Locks + Caddy subdomains torn down.")


def release_stale_lock(lock_file_path):
    """Release a stale lock file."""
    try:
        os.remove(lock_file_path)
    except:
        pass


def validate_no_collision(prj_id):
    """Check if port + DB already in use (pre-flight validation)."""
    lock_dir = os.path.expanduser("~/Desktop/Lorka/projects/.locks")
    lock_file_path = os.path.join(lock_dir, f"{prj_id}.lock")

    if os.path.exists(lock_file_path):
        try:
            with open(lock_file_path, "r") as f:
                manifest = json.load(f)
                print(f"[COLLISION CHECK] {prj_id} port {manifest['base_port']} in use by {manifest['squad_id']}")
                return False
        except:
            pass

    return True


if __name__ == "__main__":
    # Test mode
    prj_id = sys.argv[1] if len(sys.argv) > 1 else "PRJ-SAKK"
    squad_id = sys.argv[2] if len(sys.argv) > 2 else f"test-squad-{int(time.time())}"

    lock_file, manifest = acquire_project_lock(prj_id, squad_id)
    generate_dynamic_caddyfile(manifest)

    print(f"\n[TEST] Lock acquired. Press ENTER to release...")
    input()

    release_project_lock(lock_file, squad_id, manifest)
